stages:
  - test
  - build&deploy
  - notify

test:nodeunit:
  stage: test
  tags:
    - test
  script:
    - bash $(dirname $(nvm which current))/../lib/node_modules/wallaby-ci/buildscripts/${CI_JOB_NAME}.sh

test:lint:
  stage: test
  script:
    - bash $(dirname $(nvm which current))/../lib/node_modules/wallaby-ci/buildscripts/${CI_JOB_NAME}.sh
  tags:
    - test
  artifacts:
    when: on_failure
    expire_in: 30 days
    paths:
      - artifacts/

deploy:wallabycd:
  stage: build&deploy
  script:
    - export ANDROID_HOME=/opt/android-sdk-linux
    - node $(dirname $(nvm which current))/../lib/node_modules/wallaby-cd/app.js
  tags: 
    - deploy
#  only:
#    - tags

notify:rocket.chat:
  stage: notify
  script: >-
    curl -X POST --data-urlencode "payload={\"username\":\"gitlab\",\"text\":\"Build on \`$CI_COMMIT_REF_NAME\` failed! Commit \`$(git log -1 --oneline)\` See <$CI_PROJECT_URL/commit/$CI_COMMIT_SHA/pipelines>\"}" $CI_ROCKETCHAT_WEBHOOK_URL
  when: on_failure
  tags:
    - chat

# CUSTOM JOBS AFTER THIS LINE
